force-app/main/default/objects/Balance__c/Balance__c.object-meta.xml
<CustomObject>
    <label>Balance Sheet</label>
    <nameField>
        <label>Date</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Balance Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Balance__c/fields/afterContribution__c.field-meta.xml
<CustomField>
    <fullName>afterContribution__c</fullName>
    <label>Balance After Contribution</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Balance__c/fields/afterTax__c.field-meta.xml
<CustomField>
    <fullName>afterTax__c</fullName>
    <label>Balance After Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Balance__c/fields/start__c.field-meta.xml
<CustomField>
    <fullName>start__c</fullName>
    <label>Balance at Start</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SuperannuationCalculator__c/SuperannuationCalculator__c.object-meta.xml
<CustomObject>
    <label>Superannuation Calculator</label>
    <nameField>
        <label>Superannuation Calculator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Superannuation Calculators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SuperannuationCalculator__c/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <label>Tax</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/Tax.cls
public class Tax implements Formula{
    public Decimal getBalance(Decimal currentBalance, Balance__c balanceEntry, SuperannuationCalculator__c calculator){
        Decimal taxPercent = SuperCalculatorCheckRecursive.percent(calculator.Tax__c);
        balanceEntry.afterTax__c = currentBalance - (balanceEntry.afterContribution__c - balanceEntry.start__c)*taxPercent;
        return balanceEntry.afterTax__c;
    }
}