force-app/main/default/objects/Balance__c/Balance__c.object-meta.xml
<CustomObject>
    <label>Balance Sheet</label>
    <nameField>
        <label>Date</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Balance Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Balance__c/fields/Calculator__c.field-meta.xml
<CustomField>
    <fullName>Calculator__c</fullName>
    <label>Calculator</label>
    <referenceTo>SuperannuationCalculator__c</referenceTo>
    <relationshipLabel>Balance Sheets</relationshipLabel>
    <relationshipName>Balance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Balance__c/fields/start__c.field-meta.xml
<CustomField>
    <fullName>start__c</fullName>
    <label>Balance at Start</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SuperannuationCalculator__c/SuperannuationCalculator__c.object-meta.xml
<CustomObject>
    <label>Superannuation Calculator</label>
    <nameField>
        <label>Superannuation Calculator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Superannuation Calculators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SuperannuationCalculator__c/fields/sizeOfBalance__c.field-meta.xml
<CustomField>
    <fullName>sizeOfBalance__c</fullName>
    <label>Number of Balance Sheet Records</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SuperannuationCalculator__c/fields/StartingBalance__c.field-meta.xml
<CustomField>
    <fullName>StartingBalance__c</fullName>
    <label>StartingBalance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SuperannuationCalculator__c/fields/StartingMonth__c.field-meta.xml
<CustomField>
    <fullName>StartingMonth__c</fullName>
    <label>Starting Month</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <label>Annual Calculation Only</label>
            </value>
            <value>
                <fullName>January</fullName>
            </value>
            <value>
                <fullName>February</fullName>
            </value>
            <value>
                <fullName>March</fullName>
            </value>
            <value>
                <fullName>April</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>June</fullName>
            </value>
            <value>
                <fullName>July</fullName>
            </value>
            <value>
                <fullName>August</fullName>
            </value>
            <value>
                <fullName>September</fullName>
            </value>
            <value>
                <fullName>October</fullName>
            </value>
            <value>
                <fullName>November</fullName>
            </value>
            <value>
                <fullName>December</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SuperannuationCalculator__c/fields/StartingYear__c.field-meta.xml
<CustomField>
    <fullName>StartingYear__c</fullName>
    <label>Starting Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SuperCalculatorTriggerHandler.cls
//Author: Mark Collier 
//Purpose: To predict the balance of your Superannuation in the future. 
public class SuperCalculatorTriggerHandler{ 
	public List<SuperannuationCalculator__c> oldList = new List<SuperannuationCalculator__c>();//This variable is available for use so that we can easily retrieve what the records were before the transaction took place. 
	public List<SuperannuationCalculator__c> newList = new List<SuperannuationCalculator__c>();//This variable is available for use so that we can easily retrieve what the records were after the transaction took place. 
	public SuperCalculatorTriggerHandler(List<SuperannuationCalculator__c> oldListParameter,List<SuperannuationCalculator__c> newListParameter){ 
		oldList = oldListParameter; 
		newList = newListParameter; 
		main(); 
	} 
	//This method is part of the initialisation for this class and will be executed when the class is initialised. 
	public void main(){ 
		if(SuperCalculatorCheckRecursive.TriggerOn){
			delete [SELECT Id FROM Balance__c WHERE Calculator__c IN: new Map<Id,SuperannuationCalculator__c>(newList).keySet()];
			List<Balance__c> balances = new List<Balance__c>();
			for(SuperannuationCalculator__c calc:newList){
				if(!SuperCalculatorCheckRecursive.setOfIds.contains(calc.Id)){
					Balance__c balance = new Balance__c(start__c = calc.StartingBalance__c, Calculator__c = calc.Id);
					for(String balanceName:getBalanceEntryNames(calc)){
						balance.Name = balanceName;
						Decimal finalBalance = fillOutBalance(balance,new GenerateCalculationSteps(calc));
						balances.add(balance);
						balance = new Balance__c(Calculator__c = calc.Id, start__c=finalBalance);
					}
				}
			}
			insert balances;
		}	
	}
	public Decimal fillOutBalance(Balance__c currentBalance,GenerateCalculationSteps orderOfCalculation){
		Decimal balanceInc = currentBalance.start__c;
		for(String step:orderOfCalculation.steps){
			Formula operation = orderOfCalculation.mapOfSteps.get(step);
			balanceInc = operation.getBalance(balanceInc,currentBalance, orderOfCalculation.calculator);
		}
		return balanceInc;
	}
	public List<String> getBalanceEntryNames(SuperannuationCalculator__c calculator){
		DateList dates = new DateList();
        Integer m = dates.allMonthsMap.get(calculator.startingMonth__c);
        Integer startingYear = (Integer)calculator.startingYear__c;
        Integer size = (Integer)calculator.sizeOfBalance__c;
		DateHandler dateHandle = dates.mapOfDates.get(calculator.startingMonth__c);
		System.debug('m = '+m+'; sy = '+startingYear+';size = '+size);
        return dateHandle.getList(startingYear, m, size);
	}
}