force-app/main/default/objects/Balance__c/Balance__c.object-meta.xml
<CustomObject>
    <label>Balance Sheet</label>
    <nameField>
        <label>Date</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Balance Sheets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Balance__c/fields/afterContribution__c.field-meta.xml
<CustomField>
    <fullName>afterContribution__c</fullName>
    <label>Balance After Contribution</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Balance__c/fields/afterICR__c.field-meta.xml
<CustomField>
    <fullName>afterICR__c</fullName>
    <label>Balance After ICR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SuperannuationCalculator__c/SuperannuationCalculator__c.object-meta.xml
<CustomObject>
    <label>Superannuation Calculator</label>
    <nameField>
        <label>Superannuation Calculator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Superannuation Calculators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SuperannuationCalculator__c/fields/ICR__c.field-meta.xml
<CustomField>
    <fullName>ICR__c</fullName>
    <label>Indirect Cost Ratio (ICR)</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/ICR.cls
public class ICR implements Formula{
    public Decimal getBalance(Decimal currentBalance, Balance__c balanceEntry, SuperannuationCalculator__c calculator){
        Decimal icrPercent = SuperCalculatorCheckRecursive.percent(calculator.ICR__c);
        balanceEntry.afterICR__c = currentBalance-(currentBalance-balanceEntry.afterContribution__c)*icrPercent;
        return balanceEntry.afterICR__c;
    }
}