force-app/main/default/objects/Resident__c/Resident__c.object-meta.xml
<CustomObject>
    <description>Aged Care Resident</description>
    <label>Resident</label>
    <nameField>
        <label>Room Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Residents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resident__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Completed 2024</fullName>
            </value>
            <value>
                <fullName>Completed 2025</fullName>
            </value>
            <value>
                <fullName>Completed 2026</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resident__c/fields/This_Care_Plan_Evaluation__c.field-meta.xml
<CustomField>
    <fullName>This_Care_Plan_Evaluation__c</fullName>
    <label>This Care Plan Evaluation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Trig_Resident.cls
/** 
* Name: Trig_Resident
* Purpose: To update this care plan evaluation date whenever the status has changed to completed.
* 
* Who            When           Ref            What            
* -------------------------------------------------------------
* Mark Collier   17/03/2025                    Resident__c     
* -------------------------------------------------------------
**/
public class Trig_Resident implements TriggerInterface {
	/**
	* Name: beforeInsert
	* Purpose: To control and direct the necessary operations and actions required to be processed in the event that Resident__c records are inserted, updated or deleted.
	* 
	* Who            When           Ref            What                
	* -----------------------------------------------------------------
	* Mark Collier   17/03/2025                    Method was created. 
	* -----------------------------------------------------------------
	**/
	public void beforeInsert(List<SObject> newRecords){
	}
	/**
	* Name: beforeUpdate
	* Purpose: .
	* 
	* Who            When           Ref            What                
	* -----------------------------------------------------------------
	* Mark Collier   17/03/2025                    Method was created. 
	* -----------------------------------------------------------------
	**/
	public void beforeUpdate(Map<Id, SObject> mapNewRecords, Map<Id, SObject> mapOldRecords){
		for(Id residentId:mapNewRecords.keySet()){
			Resident__c newRecord = (Resident__c)mapNewRecords.get(residentId);
			if(mapOldRecords.containsKey(residentId)){
				Resident__c oldRecord = (Resident__c)mapOldRecords.get(residentId);
				if(newRecord.Status__c != oldRecord.Status__c){
					if(String.isNotBlank(newRecord.Status__c) && newRecord.Status__c != 'Open'){
						newRecord.This_Care_Plan_Evaluation__c = Date.today();
					}
				}
			}
		}
	}
	/**
	* Name: beforeDelete
	* Purpose: .
	* 
	* Who            When           Ref            What                
	* -----------------------------------------------------------------
	* Mark Collier   17/03/2025                    Method was created. 
	* -----------------------------------------------------------------
	**/
	public void beforeDelete(Map<Id, SObject> mapOldRecords){
	}
	/**
	* Name: afterInsert
	* Purpose: .
	* 
	* Who            When           Ref            What                
	* -----------------------------------------------------------------
	* Mark Collier   17/03/2025                    Method was created. 
	* -----------------------------------------------------------------
	**/
	public void afterInsert(Map<Id, SObject> mapNewRecords){
	}
	/**
	* Name: afterUpdate
	* Purpose: .
	* 
	* Who            When           Ref            What                
	* -----------------------------------------------------------------
	* Mark Collier   17/03/2025                    Method was created. 
	* -----------------------------------------------------------------
	**/
	public void afterUpdate(Map<Id, SObject> mapNewRecords, Map<Id, SObject> mapOldRecords){
	}
	/**
	* Name: afterDelete
	* Purpose: .
	* 
	* Who            When           Ref            What                
	* -----------------------------------------------------------------
	* Mark Collier   17/03/2025                    Method was created. 
	* -----------------------------------------------------------------
	**/
	public void afterDelete(Map<Id, SObject> mapOldRecords){
	}
	/**
	* Name: afterUndelete
	* Purpose: .
	* 
	* Who            When           Ref            What                
	* -----------------------------------------------------------------
	* Mark Collier   17/03/2025                    Method was created. 
	* -----------------------------------------------------------------
	**/
	public void afterUndelete(Map<Id, SObject> mapNewRecords){
	}
}