force-app/main/default/objects/Transactions__c/Transactions__c.object-meta.xml
<CustomObject>
    <label>Transactions</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transactions__c/fields/Debit__c.field-meta.xml
<CustomField>
    <fullName>Debit__c</fullName>
    <label>Debit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TransactionHandler.cls
public class TransactionHandler {
    public TransactionHandler(){
        absoluteAll();
    }
    public List<Transactions__c> query(){
        return [SELECT Debit__c FROM Transactions__c];
    }
    public void absoluteAll(){
        List<Transactions__c> empty = new List<Transactions__c>();
        for(Transactions__c cost:query()){
            if(cost.Debit__c<0){
                cost.Debit__c = - cost.Debit__c;
                empty.add(cost);
            }
        }
        update empty;
    }
}