force-app/main/default/objects/Search_Engine__c/Search_Engine__c.object-meta.xml
<CustomObject>
    <description>REST API class for Search_Engine__c</description>
    <label>Search Engine</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Search Engines</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Search_Engine__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <label>URL</label>
	<description></description>
	<encryptionScheme>None</encryptionScheme>
	<type>Text</type>
	<length>255</length>
</CustomField>

force-app/main/default/classes/Trig_SearchEngine.cls
/** 
* Name: Trig_SearchEngine
* Purpose: To find a piece of text.
* 
* Who            When           Ref            What             
* --------------------------------------------------------------
* Mark Collier   05/05/2025                    Search_Engine__c 
* --------------------------------------------------------------
**/
public class Trig_SearchEngine implements TriggerInterface {
	/**
	* Name: beforeInsert
	* Purpose: To control and direct the necessary operations and actions required to be processed in the event that Search_Engine__c records are inserted, updated or deleted.
	* 
	* Who            When           Ref            What                
	* -----------------------------------------------------------------
	* Mark Collier   05/05/2025                    Method was created. 
	* -----------------------------------------------------------------
	**/
	public void beforeInsert(List<SObject> newRecords){
	}
	/**
	* Name: beforeUpdate
	* Purpose: .
	* 
	* Who            When           Ref            What                
	* -----------------------------------------------------------------
	* Mark Collier   05/05/2025                    Method was created. 
	* -----------------------------------------------------------------
	**/
	public void beforeUpdate(Map<Id, SObject> mapNewRecords, Map<Id, SObject> mapOldRecords){
		performCallout(mapNewRecords.keySet());
	}
	@future(callout=true)
	public static void performCallout(Set<Id> recordIds){
		UtilHttpClass apiRequest = new UtilHttpClass();
		apiRequest.setEndpoint([SELECT URL__c FROM Search_Engine__c WHERE Id IN: recordIds].URL__c);
		apiRequest.setMethod('GET');
		apiRequest.setParameter(recordIds);
		SalesforceRequest callout = new SalesforceRequest(new SearchEngineRequest(),apiRequest);
		callout.send();
	}
	/**
	* Name: beforeDelete
	* Purpose: .
	* 
	* Who            When           Ref            What                
	* -----------------------------------------------------------------
	* Mark Collier   05/05/2025                    Method was created. 
	* -----------------------------------------------------------------
	**/
	public void beforeDelete(Map<Id, SObject> mapOldRecords){
	}
	/**
	* Name: afterInsert
	* Purpose: .
	* 
	* Who            When           Ref            What                
	* -----------------------------------------------------------------
	* Mark Collier   05/05/2025                    Method was created. 
	* -----------------------------------------------------------------
	**/
	public void afterInsert(Map<Id, SObject> mapNewRecords){
	}
	/**
	* Name: afterUpdate
	* Purpose: .
	* 
	* Who            When           Ref            What                
	* -----------------------------------------------------------------
	* Mark Collier   05/05/2025                    Method was created. 
	* -----------------------------------------------------------------
	**/
	public void afterUpdate(Map<Id, SObject> mapNewRecords, Map<Id, SObject> mapOldRecords){
	}
	/**
	* Name: afterDelete
	* Purpose: .
	* 
	* Who            When           Ref            What                
	* -----------------------------------------------------------------
	* Mark Collier   05/05/2025                    Method was created. 
	* -----------------------------------------------------------------
	**/
	public void afterDelete(Map<Id, SObject> mapOldRecords){
	}
	/**
	* Name: afterUndelete
	* Purpose: .
	* 
	* Who            When           Ref            What                
	* -----------------------------------------------------------------
	* Mark Collier   05/05/2025                    Method was created. 
	* -----------------------------------------------------------------
	**/
	public void afterUndelete(Map<Id, SObject> mapNewRecords){
	}
}