force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <formula>Credit__c -  Debit__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Credit__c.field-meta.xml
<CustomField>
    <fullName>Credit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Credit Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Debit__c.field-meta.xml
<CustomField>
    <fullName>Debit__c</fullName>
    <label>Debit Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction_Visibility__c/Transaction_Visibility__c.object-meta.xml
<CustomObject>
    <description>REST API class for Transaction_Visibility__c</description>
    <label>Transaction Visibility</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Visibilitys</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transactions__b/Transactions__b.object-meta.xml
<CustomObject>
    <label>Transactions</label>
    <pluralLabel>Transactions</pluralLabel>
</CustomObject>

force-app/main/default/classes/TransactionVisibility.cls
/** 
* Name: TransactionVisibility
* Purpose: To verify whether a batch will need to be executed.
* 
* Who            When           Ref            What            
* -------------------------------------------------------------
* Mark Collier   30/04/2025                    All             
* -------------------------------------------------------------
**/
public class TransactionVisibility implements Queueable, Database.AllowsCallouts {
	private Set<Id> recordIds = new Set<Id>();
	/**
	* Name: TransactionVisibility
	* Purpose: Constructor used to control and direct the neccessary operations for this Apex Class.
	* 
	* Who            When           Ref            What                     
	* ----------------------------------------------------------------------
	* Mark Collier   30/04/2025                    Constructor was created. 
	* ----------------------------------------------------------------------
	**/
	public TransactionVisibility(Set<Id> recordIdsParameter){
		recordIds = recordIdsParameter;
	}
	/**
	* Name: execute
	* Purpose: .
	* 
	* Who            When           Ref            What                
	* -----------------------------------------------------------------
	* Mark Collier   30/04/2025                    Method was created. 
	* -----------------------------------------------------------------
	**/
	public void execute(QueueableContext context) {
		Transaction_Visibility__c record = [SELECT Id,Start_Date__c,End_Date__c,Amount__c FROM Transaction_Visibility__c WHERE Id IN: recordIds];
		DateTime startDate = (DateTime)record.Start_Date__c;
		DateTime endDate = (DateTime)record.End_Date__c;
		Transaction__c t = new Transaction__c();
		Transactions__b b = new Transactions__b();
		Map<String,String> creditMap = new Map<String,String>{'Amount__c' => 'Credit__c'};
		Map<String,String> debitMap = new Map<String,String>{'Amount__c' => 'Debit__c'};
		BigObjectArchiver archiver = new BigObjectArchiver(t,b,creditMap,debitMap,'Date__c',startDate,endDate);
		List<SObject> bigObjectRecords = Database.query(archiver.archiver.getQuery('Transactions__b',false));
		TriggerFactory.bypassHandler(Trig_TransactionVisibility.class);
			record.Amount__c = bigObjectRecords.size();
			update record;
		TriggerFactory.removeAllBypassHandlers();
		if(bigObjectRecords.size()<=1000){
			Database.executeBatch(archiver,1000);
		}
	}
}