force-app/main/default/objects/SuperannuationCalculator__c/SuperannuationCalculator__c.object-meta.xml
<CustomObject>
    <label>Superannuation Calculator</label>
    <nameField>
        <label>Superannuation Calculator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Superannuation Calculators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SuperannuationCalculator__c/fields/fifth__c.field-meta.xml
<CustomField>
    <fullName>fifth__c</fullName>
    <label>5th Calcaulation</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>fourth__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Order_of_Calculation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SuperannuationCalculator__c/fields/first__c.field-meta.xml
<CustomField>
    <fullName>first__c</fullName>
    <label>1st Calculation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contribute</fullName>
            </value>
            <value>
                <fullName>Grow</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Tax</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SuperannuationCalculator__c/fields/fourth__c.field-meta.xml
<CustomField>
    <fullName>fourth__c</fullName>
    <label>4th Calculation</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>third__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Order_of_Calculation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SuperannuationCalculator__c/fields/second__c.field-meta.xml
<CustomField>
    <fullName>second__c</fullName>
    <label>2nd Calculation</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>first__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contribute</fullName>
            </value>
            <value>
                <fullName>Grow</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Tax</fullName>
            </value>
            <value>
                <fullName>ICR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SuperannuationCalculator__c/fields/third__c.field-meta.xml
<CustomField>
    <fullName>third__c</fullName>
    <label>3rd Calculation</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>second__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Order_of_Calculation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Order_of_Calculation.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Contribute</fullName>
    </customValue>
    <customValue>
        <fullName>Grow</fullName>
    </customValue>
    <customValue>
        <fullName>Fee</fullName>
    </customValue>
    <customValue>
        <fullName>Tax</fullName>
    </customValue>
    <customValue>
        <fullName>ICR</fullName>
    </customValue>
    <masterLabel>Order of Calculation</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GenerateCalculationSteps.cls
public class GenerateCalculationSteps{
    public Map<String,Formula> mapOfSteps;
    public List<String> steps;
    public SuperannuationCalculator__c calculator;
    public GenerateCalculationSteps(SuperannuationCalculator__c calc){
        calculator = calc;
        generateSteps();
        generateMap();
    }
    private void generateSteps(){
        steps = new List<String>{
            calculator.first__c,
            calculator.second__c,
            calculator.third__c,
            calculator.fourth__c,
            calculator.fifth__c
        };
    }
    private void generateMap(){
        mapOfSteps = new Map<String,Formula>();
        mapOfSteps.put('Contribute',new Contribution());
        mapOfSteps.put('Grow',new Grow());
        mapOfSteps.put('Fee',new Fee());
        mapOfSteps.put('Tax',new Tax());
        mapOfSteps.put('ICR',new ICR());
    }
}