force-app/main/default/objects/Bank__c/Bank__c.object-meta.xml
<CustomObject>
    <label>Bank</label>
    <nameField>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank__c/fields/Base_Interest__c.field-meta.xml
<CustomField>
    <fullName>Base_Interest__c</fullName>
    <label>Base Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Bank__c/fields/Saving_Account__c.field-meta.xml
<CustomField>
    <fullName>Saving_Account__c</fullName>
    <label>Saving Account</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Interest_Rate__c/Interest_Rate__c.object-meta.xml
<CustomObject>
    <label>Interest Rate</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Interest Rate ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interest Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interest_Rate__c/fields/Bank__c.field-meta.xml
<CustomField>
    <fullName>Bank__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank</label>
    <referenceTo>Bank__c</referenceTo>
    <relationshipLabel>Interest Rates</relationshipLabel>
    <relationshipName>Interest_Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interest_Rate__c/fields/Button_URL__c.field-meta.xml
<CustomField>
    <fullName>Button_URL__c</fullName>
    <label>Button URL</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Interest_Rate__c/fields/Conditions__c.field-meta.xml
<CustomField>
    <fullName>Conditions__c</fullName>
    <label>Conditions</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Interest_Rate__c/fields/Total_Interest__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest__c</fullName>
    <label>Total Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/InterestRateTriggerTest.cls
//Author: Mark Collier 
//Purpose: To test that we have achieved the following goal: 
//	-  To ensure latest bank details are updated based on the interest rates they provide in saving accounts. 
@isTest 
public class InterestRateTriggerTest{ 
	//The purpose of this method is to ensure tests are covered and errors in the trigger are detected early. 
	@isTest
	public static void insertTest(){ 
		InterestRateCheckRecursive.clear(); 
        Test.startTest();
			Interest_Rate__c record = new InterestRateTriggerDataFactory('InterestRateTriggerDataFactory').insertInterestRate(); 
			Interest_Rate__c withURL = new InterestRateTriggerDataFactory('InterestRateTriggerDataFactory').retrieveInterestRate();
			withURL.Button_URL__c = '/details?distributor=canstar&table=savingsaccounts&prod_id=-17212351454951650982&co_code=ONE&profile=Bonus Saver&amount=1000';
			insert withURL;
		Test.stopTest();
		new doQuery();
	} 
	public class doQuery extends Random{
		public doQuery(){
			List<Interest_Rate__c> rates = [SELECT Id, Base_Interest__c, Conditions__c, Date__c, Saving_Account__c, Total_Interest__c,Bank__c FROM Interest_Rate__c];
			System.debug('rates = '+rates);
		}
	}
}